#Doctrine extentions
stof_doctrine_extensions:
    default_locale: %locale%
    translation_fallback: true
    orm:
        default:
          sluggable: true
          timestampable: true
          sortable: true

#Fos User Bundle
fos_user:
    db_driver: orm
    firewall_name: admin
    user_class: Ai\AdminBundle\Entity\BeUser
    group:
        group_class: Ai\AdminBundle\Entity\BeGroup

#Sonata
sonata_admin:
    title: "%dashboard_title%"
    options:
            html5_validate: true
            confirm_exit: true
            use_select2: true
    templates:
        layout: AiAdminBundle:Admin:standard_layout.html.twig
    dashboard:
        groups:
#            sonata_app_recipes:
#                label: Рецепты:
#                label_catalogue: ~:
#                items:
#                    - app.admin.categories
#                    - app.admin.ingredients
#                    - app.admin.recipes
#                    - app.admin.measures
#                    - app.admin.measure_reduction
##                    - app.admin.recipes_ingredients
##                    - app.admin.recipes_steps
#                roles: [ROLE_SUPER_ADMIN, ROLE_SONATA_ADMIN]
            ai_admins:
                label: Администрирование:
                items:
                    - ai_admin.be_user
                    - ai_admin.be_group
#                roles: [ROLE_SUPER_ADMIN]
        blocks:
#            -
#                position: left
#                type: sonata.admin.block.admin_list
#                settings:
#                    groups: [sonata_app_recipes]
            -
                position: right
                type: sonata.admin.block.admin_list
                settings:
                    groups: [ai_admins]

sonata_block:
    default_contexts: [sonata_page_bundle]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

sonata_doctrine_orm_admin:
    entity_manager: ~
    templates:
        form:
            - AiAdminBundle:Admin:form_admin_fields.html.twig


pix_sortable_behavior:
    db_driver: orm
    position_field:
        default: position

avalanche_imagine:
    filters:
        admin_thumb:
            type:    thumbnail
            options: { size: [120, 120], mode: outbound }