services:
    ai_admin.be_user:
        class: Ai\AdminBundle\Admin\BeUserAdmin
        arguments: [~, Ai\AdminBundle\Entity\BeUser, AiAdminBundle:Admin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Настройки, label: Пользователи админки}
        calls:
            - [ setContainer, [ @service_container ] ]
            - [ setPositionService, [@pix_sortable_behavior.position]]

    ai_admin.be_group:
        class: Ai\AdminBundle\Admin\BeGroupAdmin
        arguments: [~, Ai\AdminBundle\Entity\BeGroup, AiAdminBundle:Admin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Настройки, label: Группы пользователей}
        calls:
            - [ setContainer, [ @service_container ] ]
            - [ setPositionService, [@pix_sortable_behavior.position]]