admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /

soanata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /

sonata_cache_cache:
    resource: '@SonataCacheBundle/Resources/config/routing/cache.xml'
    prefix: /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

ai_admin_retrieve_autocomplete_items:
    pattern: /core/add-autocomplete-items
    defaults: { _controller: 'ai_admin.controller.model_autocomplete:retrieveAutocompleteItemsAction' }