services:
    ai_admin.be_user:
        class: Ai\AdminBundle\Admin\BeUserAdmin
        arguments: [~, Ai\AdminBundle\Entity\BeUser, AiAdminBundle:Admin]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: settings
                label: breadcrumb.link_be_user_list
                label_translator_strategy: sonata.admin.label.strategy.underscore
                autoadmin: true
        calls:
            - [ setContainer, [ "@service_container" ] ]
            - [ setPositionService, ["@pix_sortable_behavior.position"]]

    ai_admin.be_group:
        class: Ai\AdminBundle\Admin\BeGroupAdmin
        arguments: [~, Ai\AdminBundle\Entity\BeGroup, AiAdminBundle:Admin]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: settings
                label: breadcrumb.link_be_group_list
                label_translator_strategy: sonata.admin.label.strategy.underscore
                autoadmin: true
        calls:
            - [ setContainer, [ "@service_container" ] ]
            - [ setPositionService, ["@pix_sortable_behavior.position"]]

    ai_gallery.image_manager:
        class: Ai\AdminBundle\Services\ImageManager
        arguments:
            - '@liip_imagine.cache.manager'
            - '@liip_imagine.data.manager'
            - '@liip_imagine.filter.manager'
            - '@oneup_uploader.orphanage_manager'
            - '@filesystem'
            - '%kernel.root_dir%'

    ai_admi.upload_listener:
        class: Ai\AdminBundle\EventListener\UploaderListener
        tags:
            - { name: kernel.event_listener, event: oneup_uploader.post_upload, method: onUpload }

    ai_admin.form.type.image_uploader:
        class: Ai\AdminBundle\Form\Type\ImageUploaderType
        arguments:
            - "@ai_gallery.image_manager"
            - "%form.ai_admin_image_uploader%"
        tags:
            - { name: form.type, alias: ai_admin_image_uploader }

    ai_admin.form.type.jqueryslider:
        class: Ai\AdminBundle\Form\Type\JquerySliderType
        arguments:
            - "%form.ai_admin_jqueryslider%"
        tags:
            - { name: form.type, alias: ai_admin_jqueryslider }


    ai_admin.form.type.model_autocomplete:
        class: Ai\AdminBundle\Form\Type\ModelAutocompleteType
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type, alias: ai_admin_model_autocomplete }

    ai_admin.controller.model_autocomplete:
        class: Ai\AdminBundle\Controller\ModelAutocompleteController
        arguments:
            - "@twig"
            - "@sonata.admin.pool"
            - "@sonata.admin.helper"
            - "@validator"

    ai_admin.twig.file.extension:
        class: Ai\AdminBundle\Twig\Extension\FileExtension
        tags:
            - { name: twig.extension }