services:
    ai_admin.be_user:
        class: Ai\AdminBundle\Admin\BeUserAdmin
        arguments: [~, Ai\AdminBundle\Entity\BeUser, AiAdminBundle:Admin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Настройки, label: Пользователи админки}
        calls:
            - [ setContainer, [ @service_container ] ]
            - [ setPositionService, [@pix_sortable_behavior.position]]

    ai_admin.be_group:
        class: Ai\AdminBundle\Admin\BeGroupAdmin
        arguments: [~, Ai\AdminBundle\Entity\BeGroup, AiAdminBundle:Admin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Настройки, label: Группы пользователей}
        calls:
            - [ setContainer, [ @service_container ] ]
            - [ setPositionService, [@pix_sortable_behavior.position]]

    ai_admin.form.type.jqueryslider:
        class: Ai\AdminBundle\Form\Type\JquerySliderType
        arguments:
            - "%form.ai_admin_jqueryslider%"
        tags:
            - { name: form.type, alias: ai_admin_jqueryslider }


    ai_admin.form.type.model_autocomplete:
        class: Ai\AdminBundle\Form\Type\ModelAutocompleteType
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type, alias: ai_admin_model_autocomplete }

    ai_admin.controller.model_autocomplete:
        class: Ai\AdminBundle\Controller\ModelAutocompleteController
        arguments:
            - "@twig"
            - "@sonata.admin.pool"
            - "@sonata.admin.helper"
            - "@validator"

    ai_admin.twig.file.extension:
        class: Ai\AdminBundle\Twig\Extension\FileExtension
        tags:
            - { name: twig.extension }